export type StandardSection = {
  name: string;
  icon: string;
  sortOrder: number;
  devices: string[];
};

export const STANDARD_SECTIONS: StandardSection[] = [
  {
    name: "Produktion",
    icon: "ChefHat",
    sortOrder: 0,
    devices: [
      "Vertikaltoaster 1",
      "Vertikaltoaster 2",
      "Muffin Toaster",
      "Steamer 1",
      "Steamer 2",
      "Monitor Initiator 1",
      "Monitor Initiator 2",
      "Monitor Prep Screen (2*3)",
      "UHC 1",
      "UHC 2",
      "Hierkocher",
      "Griller 1",
      "Griller 2",
      "Patty Truhe 1",
      "Patty Truhe 2",
      "B&F Ofen 1",
      "B&F Ofen 2",
      "UVC Griller",
      "UVC Friteuse",
      "UVC Pommes",
      "Monitor Pommes",
      "Monitor UHC 1",
      "Monitor UHC 2",
      "PK Schrank Küche 1",
      "PK Schrank Küche 2",
      "Saladette",
      "CK Schrank 1 (Nuggets)",
      "CK Schrank 2 (Pommes)",
      "Friteuse Allround",
      "Friteuse Pommes",
      "3D (groß)",
      "3D 2 (klein)",
    ],
  },
  {
    name: "Service",
    icon: "MonitorSpeaker",
    sortOrder: 1,
    devices: [
      "Eiswürfelbereiter Counter",
      "Eiswürfelbereiter Drive",
      "Pommes Station",
      "Getränketower",
      "Getränketower ABS",
      "Apple Pie Spender",
      "McFlurry",
      "Eis/Shake Maschine",
      "Eismaschine",
      "Kaffeemaschine Counter 1",
      "Kaffeemaschine Counter 2 links",
      "Kaffeemaschine Drive",
      "PK Schrank Counter",
      "PK Lade Drive",
      "OAT Wärmhalte",
      "Milchkühlung Drive",
      "Milchkühlung Counter 1",
      "Milchkühlung Counter 2",
      "Monitor Ausgabe 1 (OAT1)",
      "Monitor Ausgabe 2 (OAT2)",
      "Monitor Prep Screen (2*3) – 1",
      "Monitor Prep Screen (2*3) – 2",
      "Monitor Prep Screen (2*3) – 3",
      "Monitor eProd Fries 1",
      "Monitor eProd Grilled",
      "Geschirrspülmaschine",
      "Printer Haltezeiten",
      "Monitor Getränke 1",
      "Monitor Getränke 2",
      "Kassa 02",
      "Kassa 03",
      "Kassa 04",
      "Kassa 05",
      "Kassa 06",
      "Kassa 18",
    ],
  },
  {
    name: "Lobby",
    icon: "Sofa",
    sortOrder: 2,
    devices: [
      "Lobbymaschine unten",
      "Lobbymaschine oben",
      "Lobbymaschine Küche",
      "Waschmaschine",
      "Trockner",
      "Hochdruckreiniger",
      "Traktor",
      "BioShredder",
    ],
  },
  {
    name: "McCafe",
    icon: "Coffee",
    sortOrder: 3,
    devices: [
      "McCafe Vitrine",
      "McCafe Kassa",
      "Kaffeemaschine",
      "Mühle 1",
      "Mühle 2",
      "Mixer 1",
      "Mixer 2",
      "Backofen",
      "Geschirrspüler",
      "PK Schrank 1",
      "PK Schrank 2",
    ],
  },
];
